name: tower_defense
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  r_dart_library: 0.4.1
  collection: ^1.16.0
  provider: ^6.0.4
  tuple: ^2.0.1
  vector_math: ^2.1.2
  firebase_database: ^10.0.7
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_ui_auth: ^1.1.3
  flame: ^1.6.0
  badges: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/air.png
  - assets/images/electricity.png
  - assets/images/fire.png
  - assets/images/ice.png
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  fonts: []
